apiVersion: apps/v1
kind: Deployment
metadata:
  name: rc-car-landing
  labels:
    app: rc-car-landing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rc-car-landing
  template:
    metadata:
      labels:
        app: rc-car-landing
    spec:
      containers:
      - name: rc-car-landing
        image: rc-landing:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: dockerhub-creds
