apiVersion: v1
kind: Service
metadata:
  name: rc-car-landing-service
  labels:
    app: rc-car-landing
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: rc-car-landing
