name: RC Car Landing Page CI/CD

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: |
        echo "Running tests..."
        # Uncomment when you add tests
        # npm test
        
    - name: Build Docker image
      run: |
        docker build -t debabratap/rc-landing:${{ github.sha }} .
        docker tag debabratap/rc-landing:${{ github.sha }} debabratap/rc-landing:latest
      
    - name: Login to DockerHub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push to DockerHub
      if: github.event_name != 'pull_request'
      run: |
        docker push debabratap/rc-landing:${{ github.sha }}
        docker push debabratap/rc-landing:latest
        
    - name: Deploy to Development
      if: github.ref == 'refs/heads/develop' && github.event_name != 'pull_request'
      run: |
        echo "Deploying to development environment..."
        # Add deployment steps for dev environment
        
    - name: Deploy to Production
      if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
      run: |
        echo "Deploying to production environment..."
        # Add deployment steps for production environment
